CREATE TABLE IF NOT EXISTS arrival
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY                 NOT NULL,
    color               VARCHAR(50)                                             NOT NULL,
    cotton_part         INTEGER CHECK (cotton_part BETWEEN 0 AND 100)	        NOT NULL,
    quantity            INTEGER CHECK (quantity > 0)		                    NOT NULL,

    CONSTRAINT pk_arrival PRIMARY KEY (id)
);